# Generated by Django 5.0.6 on 2024-08-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contactus_donation_volunteer_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='donation',
            name='reference',
            field=models.CharField(default='Y', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
