# Generated by Django 5.0.6 on 2024-08-14 15:16

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
