# Generated by Django 5.0.6 on 2024-08-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_news_body_rendered_alter_news_body'),
        ('api', '0012_alter_donation_id'),
    ]

    operations = [
    ]
