# Generated by Django 5.0.6 on 2024-08-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20240819_0125'),
        ('api', '0015_gallery'),
    ]

    operations = [
    ]
