# Generated by Django 5.0.6 on 2024-08-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_0013_merge_20240819_0125_0015_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('Money', 'Money'), ('Food', 'Food'), ('Clothing', 'Clothing')], default='money', max_length=10),
            preserve_default=False,
        ),
    ]
