# Generated by Django 5.0.6 on 2024-08-29 14:16

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_donation_donation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
